### ISSUE TITLE
PlaceAd with invalid MoveInDate crashes

### ISSUE THREAD

**Issue by zaraa101** [scg-unibe-ch/ese2016-team3#118]
Area Path: PlaceAd form, Homepage
Reported on: 9.12.2016
Environment: Win 10, Chrome

Description: 
- Place a new Ad
- Title : a  Street: a   City: pick a city from list like Bern   Move in date:1  Squaremeters :1 
   Number of Rooms : 1   normal Price: 1000 Description : f
- click on submit -> crashes

Expected result: There should come a error message, saying it was an invalid move in date input
[Error 500 Server Error.pdf](https://github.com/scg-unibe-ch/ese2016-team3/files/642944/Error.500.Server.Error.pdf)

**Comment by zaraa101** [comment]
Same error occurs when setting move in date to 1 in EditAd

**Comment by meggima** [comment]
Maybe a regex on the form would be a solution? (similar to the regex for the city)

Possible regex: ^(0[1-9]|[1-2][0-9]|3[0-1])-(0[1-9]|1[0-2])-[0-9]{4}$

**Comment by zaraa101** [comment]
Same error occurs when setting auction end or start date to 1.
